### ISSUE TITLE
Invalid usernames at registration

### ISSUE THREAD

**Issue by harwoeck** [philipp-r99/NoteManager#2]
There is no check against the username at the registration process.

```php
// Php regex function:
// int preg_match(string $pattern , string $subject)

if (preg_match("[A-Za-z0-9_]{6,64}", $username) == 1) {
  // Do registriation
}
```

**Comment by philipp-r99** [comment]
We are not validating any input, because it's only a little project. And we won't go public with it.
So there is no reason to validate our inputs, because it's only for own use!
But you are right, if we would publish it, we should validate inputs but not only in php also in js to show the wrong input at runtime(AngularJS).
Anyway thanks :+1:
